site_name: SEC555 Wiki
site_description: 'SANS SEC555 Class Wiki'
site_author: 'Justin Henderson'

nav:
  - Home: 
    - 'Home': 'index.md'
  - Setup:  
    - 'Setup Quick Nav': 'Labs/setup/quicknav.md'
    - 'Setup A': 'Labs/setup/A/sec555.setup.a.md'
    - 'Setup B': 'Labs/setup/B/sec555.setup.b.md'
  - Labs:
    - 'Lab Quick Nav': 'Labs/quicknav.md'
    - 555.1:
      - 'Lab 1.0 - Labs Overview': 'Labs/555_1/0/sec555.1.0.md'
      - 'Lab 1.1 - Introduction to SOF-ELK': 'Labs/555_1/1/sec555.1.1.md'
      - 'Lab 1.2 - Log Ingestion from Files and Network Connections': 'Labs/555_1/2/sec555.1.2.md'
      - 'Lab 1.3 - Log Enrichment and Parsing': 'Labs/555_1/3/sec555.1.3.md'
      - 'Lab 1.4 - Tactical Alerting': 'Labs/555_1/4/sec555.1.4.md'
    - 555.2:
      - 'Lab 2.1 - Catching the Adversary with DNS': 'Labs/555_2/1/sec555.2.1.md'
      - 'Lab 2.2 - Investigating HTTP': 'Labs/555_2/2/sec555.2.2.md'
      - 'Lab 2.3 - HTTPS Analysis': 'Labs/555_2/3/sec555.2.3.md'
    - 555.3:
      - 'Lab 3.1 - Windows Log Filtering': 'Labs/555_3/1/sec555.3.1.md'
      #- 'Lab 3.2 - Catching Evil with Windows Logs': 'Labs/555_3/2/sec555.3.2.md'
      #- 'Lab 3.3 - Logon Monitoring': 'Labs/555_3/3/sec555.3.3.md'
    #- 555.4
      #- 'Lab 4.1 - Master Inventory': 'Labs/555_4/1/sec555.4.1.md'
      #- 'Lab 4.2 - PowerShell Compromise': 'Labs/555_4/2/sec555.4.2.md'
      #- 'Lab 4.3 - NetFlow Detection': 'Labs/555_4/3/sec555.4.3.md'
    #- 555.5
      #- 'Lab 5.1 - Alert Context': 'Labs/555_5/1/sec555.5.1.md'
      #- 'Lab 5.2 - Virtual Tripwires': 'Labs/555_5/2/sec555.5.2.md'
      #- 'Lab 5.3 - Beacon Detection': 'Labs/555_5/3/sec555.5.3.md'

#theme: readthedocs
theme:
  name: 'material'
#  palette:
#    primary: 'white'
#    accent: 'indigo'
#  logo:
#   icon: 'imgs/sans-logo.png:'
#    icon: 'dashboard'
  feature:
    tabs: true
#  font: false
#  include_sidebar: false
  custom_dir: './material'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      toc_depth: "1-5"
#      permalink: true
# per https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
    - search
    - minify:
        minify_html: true
#    - pdf-export:
#          verbose: false
#          media_type: print
#          combined: false
          #combined_output_path: 508-workbook.pdf
#          enabled_if_env: ENABLE_PDF_EXPORT
extra_css:
#  - css/pdf.css
  - css/html.css
